### ISSUE TITLE
Readme Notes

### ISSUE THREAD

**Issue by ansermino** [ShyftNetwork/shyft_go-ethereum#104]
Just some notes from trying the README.md (Docker Images) on the rollback-dev branch, some are burning issues, others are mere suggestions:

- [x] Missing `--reset` flag in `./shyft-geth.sh # clears persisted directories prior to docker build` 

- [x] Ordering of `docker-compose up` and `docker-compose up --build` is confusing. Seems `--build` should be shown first and an explanation should be bolded. Use of the terms `reinitialize/rebuild` does not imply this needs to be run upon first setup.

- [x] `Docker Block Explorer` ->  Format user, password, DB fields in a more readable way (perhaps block comment using `>`)

- [x] Invalid formatting at `_The Postgres Database...` under `Docker Block Explorer Api`

- [x] Include list of services for the `To rebuild any one of the services...`

May add more as I go.

**Comment by dutterbutter** [comment]
https://shyftnetwork.github.io/go-empyrean/#introduction for review

**Comment by ansermino** [comment]
The formatting is a bit weird for the `docker-compose up` commands.

Its a bit unclear why we would use `--setup` when starting docker as opposed to `--reset`.

**Comment by dutterbutter** [comment]
Thank you for the feedback, will include changes.
