### ISSUE TITLE
seemlingly random transactions from first default account being created for no apparent reason

### ISSUE THREAD

**Issue by hhicks13** [ShyftNetwork/shyft_go-ethereum#114]
#### System information
OS & Version: Linux Ubuntu 16.04.5 LTS
Geth version 1.8.16

#### Expected behaviour
I would expect there to be no transactions, since I am not creating any. 

#### Actual behaviour
There is a constant stream of transactions coming from the first default account

#### Steps to reproduce the behaviour
Just using the block explorer seems to do this. Is it triggering a test for some reason?
![screen shot 2018-10-17 at 7 01 03 pm](https://user-images.githubusercontent.com/31278553/47121558-17df0880-d241-11e8-94ea-b98a156891c6.png)

**Comment by dbkbali** [comment]
@hhicks13 could you clarify the following:

1. Which branch are you running?

2. Are you running in docker?

If you are running the staging branch, at startup mining is turned on by default, it is possible the transactions you are seeing are mining transactions, as I believe if mining is turned on the node will mine empty blocks

**Comment by dutterbutter** [comment]
Closing this as it has become inactive.
