### ISSUE TITLE
UI Error

### ISSUE THREAD

**Issue by dutterbutter** [ShyftNetwork/shyft_go-ethereum#116]
#### Expected behaviour
Should not error when selecting account details

#### Actual behaviour
It errors out while selecting account details.

#### Steps to reproduce the behaviour
Go to [this url](`http://35.193.186.78/accounts`) and then select account address 0x9db76b4bbaea76dfda4552b7b9d4e9d43abc55fd

You will see this error message.

![screen shot 2018-10-26 at 1 03 12 pm](https://user-images.githubusercontent.com/29983536/47581880-b72a8c80-d920-11e8-8671-f23ada79985f.png)

#### Backtrace

````
[backtrace]
````

**Comment by dbkbali** [comment]
@dutterbutter  which branch ?

**Comment by ansermino** [comment]
@dbkbali seems to be a common point of confusion, perhaps let's add a branch field to the issue template?

**Comment by amerameen** [comment]
Reopening this since @larry-shyft ran into this issue today

**Comment by dbkbali** [comment]
@amerameen could you please detail what branch this is being run ? as per @ansermino we should develop some issues templates as for many of the issues being filed people are not specifying which **Branch** they are seeing this behaviour. When people are specifying issues given that development, staging, and master branches are very different it is essential that the **branch** where the behaviour is being observed be specified.

**Comment by larry-shyft** [comment]
I got it Branch staging.
