### ISSUE TITLE
Failing Tests

### ISSUE THREAD

**Issue by GregTheGreek** [ShyftNetwork/shyft_go-ethereum#119]
This is directly related to PR #118 

Tests have been updated and are green with a few exceptions:

Skipping tests in ./console directory --> Still trying to diagnosis the issue
Skipping tests in peer_test.go --> Still trying to diagnosis the issue
Skipping test testGetCHTProofs in handler_test.go --> Still trying to diagnosis the issue

**Comment by dutterbutter** [comment]
These tests seem to be passing fine with the latest upstream branch

**Comment by dutterbutter** [comment]
closing this issue as tests are passing with the latest upstream changes with PR #122
