### ISSUE TITLE
Block Explorer UI only displays records when accessing from localhost

### ISSUE THREAD

**Issue by larry-shyft** [ShyftNetwork/shyft_go-ethereum#77]
Hi Team,

When accessing from outside the server itself, the Block Explorer UI does not connect to the Block Explorer API correctly.

#### System information

Geth version: shyftgeth 1.8.3
OS & Version: Ubuntu 16.04

#### Expected behaviour
The Block Explorer UI should display records about transactions, accounts, and blocks.

#### Actual behaviour
The Block Explorer UI displays empty records.

#### Steps to reproduce the behaviour
clone the repo
docker-compose up -d 
access block explorer ui using a browser not on the server itself

#### Backtrace

WebSocket connection to 'ws://ec2-18-204-231-31.compute-1.amazonaws.com/sockjs-node/988/3qcqilyg/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400
WebSocketBrowserDriver @ websocket.js:6
WebSocketTransport @ websocket.js:32
./node_modules/sockjs-client/lib/main.js.SockJS._connect @ main.js:219
./node_modules/sockjs-client/lib/main.js.SockJS._receiveInfo @ main.js:193
g @ emitter.js:30
./node_modules/sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:50
(anonymous) @ info-receiver.js:67
g @ emitter.js:30
./node_modules/sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:50
(anonymous) @ info-ajax.js:37
g @ emitter.js:30
./node_modules/sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:50
xhr.onreadystatechange @ abstract-xhr.js:124

@GregTheGreek @dbkbali @dutterbutter @strangepowers @chris-shyft @priom

**Comment by GregTheGreek** [comment]
Pretty sure we need to change the base url of the blockexplorerUI to 0.0.0.0 and replace all the hardcoded places where api requests are being made from.

**Comment by GregTheGreek** [comment]
@CFDevelopment can you branch off of development and make the changes accrodingly please.

**Comment by chrisfenos** [comment]
Makes sense. I’ll make sure to change the hardcoded URL’s to reference the constant BASE API and then look into proxying to the API

**Comment by larry-shyft** [comment]
I am running the latest development branch on an AWS EC2 instance.
http://ec2-18-204-231-31.compute-1.amazonaws.com:3000/blocks gives empty records.

However, using VNC Viewer to remote in, then browse localhost:3000/blocks gives correct info

**Comment by dutterbutter** [comment]
@larry-shyft When I look at the network connection from the AWS EC2 Instance for some reason http://0.0.0.0:8080/ is resolving to http://localhost:8080/. Looking into why that would be now.

**Comment by priom** [comment]
@larry-shyft did u setup reverse proxy with nginx for this node?

**Comment by larry-shyft** [comment]
Yes. so http://ec2-18-204-231-31.compute-1.amazonaws.com/blocks also works

**Comment by dbkbali** [comment]
I believe the fix for this is to:

1) is to configure a proxy within axios in the blockexplorer ui app;
2) to use relative urls throughout our blockexplorer ui file similar to this example https://github.com/axios/axios/issues/1679#issuecomment-407406296

that hopefully will resolve this issue. Give us some time to implement and test

**Comment by larry-shyft** [comment]
The latest development branch fix Issue 77.  http://ec2-18-204-231-31.compute-1.amazonaws.com/blocks now gives block info
